// Generates bm/index.html from index.html by swapping in Bahasa Malaysia
// text wherever a data-i18n / data-i18n-attr marker is present. Run before
// `vite`/`vite build` (see the predev/prebuild scripts in package.json) so
// index.html stays the single source of truth for markup/structure.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'node-html-parser';
import { translations } from './bm-translations.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, '..');
const sourcePath = path.join(projectRoot, 'index.html');
const outDir = path.join(projectRoot, 'bm');
const outPath = path.join(outDir, 'index.html');

function translate(key, context) {
  const value = translations[key];
  if (value === undefined) {
    throw new Error(`Missing BM translation for key "${key}" (${context})`);
  }
  return value;
}

const root = parse(readFileSync(sourcePath, 'utf-8'));

root.querySelector('html')?.setAttribute('lang', 'ms');

root.querySelectorAll('[data-i18n]').forEach((el) => {
  const key = el.getAttribute('data-i18n');
  if (!key) return;
  el.set_content(translate(key, `data-i18n on <${el.rawTagName}>`));
});

root.querySelectorAll('[data-i18n-attr]').forEach((el) => {
  const spec = el.getAttribute('data-i18n-attr') ?? '';
  spec
    .split(';')
    .map((pair) => pair.trim())
    .filter(Boolean)
    .forEach((pair) => {
      const [attr, key] = pair.split(':').map((part) => part.trim());
      el.setAttribute(attr, translate(key, `data-i18n-attr="${attr}" on <${el.rawTagName}>`));
    });
});

const banner = `<!--
  AUTO-GENERATED by scripts/generate-bm-page.mjs — do not edit directly.
  Edit index.html (structure/markers) and scripts/bm-translations.mjs (Malay
  text), then re-run \`npm run dev\` or \`npm run build\` to regenerate this file.
-->
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, banner + root.toString() + '\n');
console.log('Generated bm/index.html');
